"""Parser for saved reports generated by mjai-reviewer.

This module intentionally returns report-shaped data only. It does not attempt
to interpret actions or classify mistakes as Mahjong-domain logic.
"""

import json
import re
from html import unescape
from typing import Any
from urllib.parse import unquote

from bs4 import BeautifulSoup, Tag

from app.models.report import ActionEvaluation, Decision, ParsedReport, ReportMetadata, Round


class UnsupportedReportError(ValueError):
    pass


class MalformedReportError(ValueError):
    pass


def _number(value: str | None) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except ValueError:
        return None


def _tile_text(node: Tag) -> str:
    tiles = [use.get("href", "").removeprefix("#pai-") for use in node.select("use.face")]
    return " ".join(tiles)


def _action_text(node: Tag) -> str:
    text = " ".join(node.get_text(" ", strip=True).split())
    text = re.sub(r"^(?:Player|Mortal):\s*", "", text)
    tiles = _tile_text(node)
    return f"{text} {tiles}".strip() if tiles else text


def _action_after_role(role: Tag) -> str:
    """Read only the action immediately following a Player/Mortal label."""
    words: list[str] = []
    tiles: list[str] = []
    for item in role.next_elements:
        if isinstance(item, Tag) and item is not role and item.select_one(".role"):
            break
        if isinstance(item, Tag) and item.name == "br":
            break
        if isinstance(item, Tag) and item.name == "svg":
            use = item.select_one("use.face")
            if use:
                tiles.append(str(use.get("href", "")).removeprefix("#pai-"))
            continue
        if isinstance(item, str):
            value = " ".join(item.split())
            if value:
                words.append(value)
        if isinstance(item, Tag) and item.name in {"details", "table"}:
            break
    text = " ".join(words).strip()
    return re.sub(r"^(?:Player:|Mortal:|プレイヤー:)\s*", "", f"{text} {' '.join(tiles)}".strip(), flags=re.I)


def _raw_value(cell: Tag) -> str | None:
    value = cell.find(attrs={"title": True})
    if value:
        return str(value.get("title"))
    # Older Japanese reports omit title attributes and render the number as
    # adjacent int/frac spans, e.g. "52." + "47492".
    text = cell.get_text("", strip=True).replace(" ", "")
    match = re.search(r"-?\d+\.\d+", text)
    return match.group(0) if match else None


def _parse_game_log(block: Tag) -> dict[str, Any] | None:
    textarea = block.find("textarea")
    candidates = [textarea.get_text() if textarea else ""]
    iframe = block.find("iframe")
    if iframe and iframe.get("src"):
        src = unescape(str(iframe["src"]))
        if "#json=" in src:
            candidates.append(src.split("#json=", 1)[1])
    for candidate in candidates:
        try:
            parsed = json.loads(unquote(candidate.strip()))
        except (json.JSONDecodeError, TypeError):
            continue
        if isinstance(parsed, dict) and "log" in parsed:
            return parsed
    return None


def _parse_decision(entry: Tag) -> Decision:
    summary = entry.find("summary")
    summary_text = summary.get_text(" ", strip=True) if summary else None
    turn_match = re.search(r"(?:Turn\s*|第\s*|(?<!\d))([0-9]+)(?:巡目)?", summary_text or "", re.I)
    shanten_match = re.search(r"(-?\d+)\s+shanten", summary_text or "", re.I)
    actual = mortal = None
    for role in entry.select(".role"):
        node = role.parent if isinstance(role.parent, Tag) else role
        action = _action_after_role(role)
        if not action:
            action = _action_text(node)
        role_name = role.get_text(strip=True).lower()
        if role_name.startswith("player") or role_name.startswith("プレイヤー"):
            actual = action
        elif role_name.startswith("mortal"):
            mortal = action

    evaluations: list[ActionEvaluation] = []
    # Fuuro tiles are current open melds, not part of the concealed hand.
    # Selecting every descendant `use.face` duplicated called tiles in the
    # public hand state because the replay also exposes them as melds.
    tile_nodes = entry.select("ul.tehai-state > li:not(.fuuro) use.face")
    draw_node = entry.select_one("ul.tehai-state > li[before] use.face") or entry.select_one("ul.tehai-state > li.tsumo use.face")
    if draw_node is None and len(tile_nodes) == 14:
        draw_node = tile_nodes[-1]
    hand = [use.get("href", "").removeprefix("#pai-") for use in tile_nodes if use is not draw_node]
    drawn = None
    if draw_node:
        drawn = draw_node.get("href", "").removeprefix("#pai-")
    table = entry.select_one("table.data")
    if table:
        # mjai-reviewer omits optional closing tags in its compact output;
        # split rows before reparsing so one malformed row cannot swallow the rest.
        row_fragments = re.split(r"<tr\b[^>]*>", table.decode_contents(), flags=re.I)[1:]
        for fragment in row_fragments:
            parts = re.split(r"<td\b[^>]*>", fragment.split("</tbody>", 1)[0], flags=re.I)[1:]
            cells = [BeautifulSoup(part, "html.parser") for part in parts[:3]]
            if len(cells) < 3:
                continue
            raw_q = _raw_value(cells[1])
            raw_policy = _raw_value(cells[2])
            evaluations.append(ActionEvaluation(
                action=_action_text(cells[0]),
                q_value=_number(raw_q),
                policy_probability_percent=_number(raw_policy),
                raw_action=cells[0].get_text(" ", strip=True),
                raw_q_value=raw_q,
                raw_policy_probability=raw_policy,
            ))
    return Decision(
        turn=int(turn_match.group(1)) if turn_match else None,
        turn_label=summary_text,
        shanten=int(shanten_match.group(1)) if shanten_match else None,
        actual_action=actual,
        mortal_action=mortal,
        legal_actions=evaluations,
        raw_summary=summary_text,
        concealed_hand=hand,
        drawn_tile=drawn,
    )


def parse_mjai_reviewer_html(document: bytes | str) -> ParsedReport:
    soup = BeautifulSoup(document, "html.parser")
    title = soup.select_one("h1.title")
    if not title or "mjai-reviewer" not in soup.get_text(" ", strip=True).lower():
        raise UnsupportedReportError("The uploaded HTML is not an mjai-reviewer report")

    metadata: dict[str, str] = {}
    for dl in soup.select("details dl"):
        terms = dl.find_all("dt", recursive=False)
        for term in terms:
            value = term.find_next_sibling("dd")
            if value:
                metadata[term.get_text(" ", strip=True).lower()] = value.get_text(" ", strip=True)
    # Saved reports are intentionally compact and commonly omit closing tags.
    # In that form BeautifulSoup exposes the whole metadata list as one node,
    # so recover only the known fields from its text without guessing values.
    metadata_text = " ".join(dl.get_text(" ", strip=True) for dl in soup.select("details dl"))
    known_keys = [
        "engine", "AI", "model tag", "softmax temperature (τ)", "softmax temperature (t)",
        "game length", "対局の長さ", "player id", "プレイヤーID", "loading time",
        "ロード時間", "review time", "検討時間", "rating", "matches/total",
        "AI一致率", "mjai-reviewer version", "mjai-reviewerバージョン", "生成日時", "generated at",
    ]
    key_pattern = "|".join(re.escape(key) for key in sorted(known_keys, key=len, reverse=True))
    for match in re.finditer(rf"(?P<key>{key_pattern})\s*(?P<value>.*?)(?=\s+(?:{key_pattern})\s*|$)", metadata_text, re.I):
        metadata[match.group("key").lower()] = match.group("value").strip()
    engine = metadata.get("engine") or metadata.get("ai")
    if engine != "Mortal":
        raise UnsupportedReportError("The report does not contain Mortal metadata")

    model_key = "model tag"
    player_key = "player id"
    version_key = next((key for key in metadata if ("version" in key and "reviewer" in key) or "バージョン" in key), None)
    parsed_metadata = ReportMetadata(
        engine=engine,
        mortal_model_version=metadata.get(model_key),
        softmax_temperature=_number(metadata.get("softmax temperature (τ)") or metadata.get("softmax temperature (t)")),
        analyzed_player=int(metadata[player_key]) if metadata.get(player_key, "").isdigit() else (int(metadata.get("プレイヤーid", "-1")) if metadata.get("プレイヤーid", "-1").isdigit() else None),
        reviewer_version=metadata.get(version_key) if version_key else None,
        raw=metadata,
    )

    rounds: list[Round] = []
    headings = soup.select("h1.kyoku-heading")
    if not headings:
        raise MalformedReportError("The mjai-reviewer report contains no kyoku sections")
    for heading in headings:
        round_id = heading.get("id")
        if not round_id:
            raise MalformedReportError("A kyoku section is missing its id")
        label_node = heading.select_one(".chapter")
        result_node = heading.select_one(".end-status")
        decisions: list[Decision] = []
        game_log = None
        sibling = heading.find_next_sibling()
        while sibling and not (isinstance(sibling, Tag) and sibling.name == "h1" and "kyoku-heading" in sibling.get("class", [])):
            if isinstance(sibling, Tag):
                if sibling.select_one("details.entry"):
                    decisions.extend(_parse_decision(entry) for entry in sibling.select("details.entry"))
                if game_log is None:
                    game_log = _parse_game_log(sibling)
            sibling = sibling.find_next_sibling()
        rounds.append(Round(id=str(round_id), label=label_node.get_text(" ", strip=True) if label_node else None,
                            result=result_node.get_text(" ", strip=True) if result_node else None,
                            decisions=decisions, original_game_log=game_log))
    return ParsedReport(metadata=parsed_metadata, rounds=rounds, embedded_game_log=next((r.original_game_log for r in rounds if r.original_game_log), None))
